[package]
name = "fsocks"
version = "0.1.0"
authors = ["jim_ <769925821@qq.com>"]

[dependencies]
tokio = "0.1.7"
libc = "0.2.42"
lru-cache = "0.1.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clap = "2.31.2"